# Generated by Django 2.2 on 2020-02-05 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alcance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, verbose_name='Descripción de alcance')),
                ('estatus', models.BooleanField(verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'Catálogo de alcance',
            },
        ),
        migrations.CreateModel(
            name='Eje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Eje')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'eje',
                'verbose_name_plural': 'ejes',
            },
        ),
        migrations.CreateModel(
            name='Subeje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Sub-Eje')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estatus', models.BooleanField(verbose_name='Estatus')),
                ('eje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Eje', verbose_name='Eje Principal')),
            ],
            options={
                'verbose_name': 'tema',
                'verbose_name_plural': 'temas',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estatus', models.BooleanField(verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidades de medida',
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('estatus', models.BooleanField(verbose_name='Estatus')),
                ('unidadMedida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.UnidadMedida')),
            ],
            options={
                'verbose_name': 'Indicador de medición',
                'verbose_name_plural': 'Indicadoress de medición',
            },
        ),
        migrations.CreateModel(
            name='GaleriaSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='', verbose_name='Imagen')),
                ('estatus', models.BooleanField(verbose_name='Estatus')),
                ('subeje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Eje', verbose_name='Sub-Eje')),
            ],
            options={
                'verbose_name': 'foto',
                'verbose_name_plural': 'fotos',
            },
        ),
        migrations.CreateModel(
            name='SubIndicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Indicador')),
                ('subeje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Subeje')),
            ],
            options={
                'verbose_name': 'Detalle de indicadores',
                'verbose_name_plural': 'Detalles de indicadores',
                'unique_together': {('indicador', 'subeje')},
            },
        ),
        migrations.CreateModel(
            name='SubBeneficiarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('alcance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Alcance')),
                ('subeje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Subeje')),
            ],
            options={
                'verbose_name': 'Detalle de beneficiarios',
                'verbose_name_plural': 'Detalles de beneficiarios',
                'unique_together': {('alcance', 'subeje')},
            },
        ),
    ]
