# Generated by Django 2.2 on 2020-02-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eje',
            name='imagen',
            field=models.ImageField(default='null', upload_to='', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
