# Generated by Django 2.2 on 2020-03-20 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eje_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('año', models.CharField(max_length=500)),
                ('estatus', models.BooleanField(verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'informe',
                'verbose_name_plural': 'informes',
            },
        ),
        migrations.AddField(
            model_name='eje',
            name='informe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Informe', verbose_name='Informe'),
        ),
    ]
