# Generated by Django 2.2 on 2020-03-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200320_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='subeje',
            name='imagen',
            field=models.ImageField(null=True, upload_to='', verbose_name='Imagen'),
        ),
    ]
