# Generated by Django 2.2.13 on 2020-07-25 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subeje_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='eje',
            name='estatus',
            field=models.BooleanField(default=True, verbose_name='Estatus'),
        ),
        migrations.AddField(
            model_name='eje',
            name='numero',
            field=models.CharField(default=1, max_length=200, verbose_name='Número'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informe',
            name='imagen',
            field=models.ImageField(null=True, upload_to='', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='galeriasub',
            name='subeje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Eje', verbose_name='Galeria Eje'),
        ),
        migrations.CreateModel(
            name='PublicacionEspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('estatus', models.BooleanField(verbose_name='Estatus')),
                ('imagen', models.ImageField(null=True, upload_to='', verbose_name='Imagen')),
                ('eje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Eje', verbose_name='Eje Principal')),
            ],
            options={
                'verbose_name': 'Publicación especial',
                'verbose_name_plural': 'Publicaciones Especiales',
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('estatus', models.BooleanField(verbose_name='Estatus')),
                ('imagen', models.ImageField(null=True, upload_to='', verbose_name='Imagen')),
                ('eje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Eje', verbose_name='Eje Principal')),
            ],
            options={
                'verbose_name': 'publicación',
                'verbose_name_plural': 'publicaciones',
            },
        ),
        migrations.CreateModel(
            name='Especial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del apartado Especial')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='', verbose_name='Imagen')),
                ('estatus', models.BooleanField(default=True, verbose_name='Estatus')),
                ('informe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Informe', verbose_name='Informe')),
            ],
            options={
                'verbose_name': 'Apartado Especial',
                'verbose_name_plural': 'Apartados Espceciales',
            },
        ),
    ]
