# Generated by Django 2.2.13 on 2020-07-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200725_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='eje',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='informe',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
