# Generated by Django 2.2.13 on 2020-07-31 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200729_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacionespecial',
            name='eje',
        ),
        migrations.AddField(
            model_name='publicacionespecial',
            name='epecial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Especial', verbose_name='Evento Especial'),
        ),
    ]
