# Generated by Django 2.2.13 on 2020-08-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200731_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='eje',
            name='decoracion',
            field=models.CharField(max_length=200, null=True, verbose_name='Color base'),
        ),
        migrations.AddField(
            model_name='informe',
            name='decoracion',
            field=models.CharField(max_length=200, null=True, verbose_name='Color Principal del Informe'),
        ),
    ]
