# Generated by Django 2.2.13 on 2020-09-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200806_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500, verbose_name='Titulo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('mapa', models.CharField(max_length=500, verbose_name='Mapa')),
                ('link', models.CharField(max_length=800, verbose_name='Link del Mapa')),
                ('estatus', models.BooleanField(verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'Visor',
                'verbose_name_plural': 'Visores',
            },
        ),
    ]
