# Generated by Django 2.2.13 on 2020-09-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_visores'),
    ]

    operations = [
        migrations.AddField(
            model_name='eje',
            name='video',
            field=models.FileField(null=True, upload_to='uploads/', verbose_name='Video Promocional'),
        ),
    ]
