# Generated by Django 2.2.13 on 2020-09-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_eje_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='visores',
            name='color',
            field=models.CharField(max_length=100, null=True, verbose_name='Color del bonto'),
        ),
        migrations.AddField(
            model_name='visores',
            name='icono',
            field=models.CharField(max_length=100, null=True, verbose_name='Icono del bonto'),
        ),
    ]
