# Generated by Django 2.2.13 on 2020-09-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200925_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='especial',
            name='video',
            field=models.FileField(null=True, upload_to='uploads/', verbose_name='Video Promocional'),
        ),
    ]
