# Generated by Django 2.2.13 on 2020-09-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_especial_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='eje',
            name='titulo',
            field=models.CharField(max_length=200, null=True, verbose_name='Titulo'),
        ),
    ]
