# Generated by Django 2.2.13 on 2020-10-19 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_informe_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='visores',
            name='eje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Eje', verbose_name='Eje'),
        ),
    ]
