# Generated by Django 2.2.13 on 2020-10-26 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_visores_eje'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='', verbose_name='Imagen')),
                ('estatus', models.BooleanField(verbose_name='Estatus')),
                ('informe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Informe', verbose_name='Informe')),
            ],
            options={
                'verbose_name': 'foto informe',
                'verbose_name_plural': 'fotos informe',
            },
        ),
    ]
