# Generated by Django 2.2.13 on 2020-10-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_galeriainf'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='video',
            field=models.FileField(null=True, upload_to='uploads/', verbose_name='Video Promocional'),
        ),
    ]
